# Generated by Django 5.1.2 on 2024-10-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_created_at_note_photo_note_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='text',
        ),
    ]
